### Check the health of the API
curl -i http://localhost:3000/api/v1/health

#### Get all buildings
curl -i http://localhost:3000/api/v1/buildings

#### Create a new building
curl -i -X POST http://localhost:3000/api/v1/buildings \
  -H "Content-Type: application/json" \
  -d '{
    "name": "Pavillon principal",
    "address": "7000, rue Marie-Victorin",
    "yearBuilt": 2005
  }'

#### Get a building by ID
curl -i http://localhost:3000/api/v1/buildings/1

#### Get a building with a non-existent ID (expects 404)
curl -i http://localhost:3000/api/v1/buildings/9999
